// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: address.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO addresses (
  client_id,
  title,
  city,
  street,
  phone,
  zip,
  lat,
  long
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, client_id, title, city, street, phone, zip, lat, long, created_at, updated_at
`

type CreateAddressParams struct {
	ClientID int64         `json:"client_id"`
	Title    string        `json:"title"`
	City     string        `json:"city"`
	Street   pgtype.Text   `json:"street"`
	Phone    pgtype.Text   `json:"phone"`
	Zip      pgtype.Text   `json:"zip"`
	Lat      pgtype.Float4 `json:"lat"`
	Long     pgtype.Float4 `json:"long"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.ClientID,
		arg.Title,
		arg.City,
		arg.Street,
		arg.Phone,
		arg.Zip,
		arg.Lat,
		arg.Long,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Title,
		&i.City,
		&i.Street,
		&i.Phone,
		&i.Zip,
		&i.Lat,
		&i.Long,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM addresses
WHERE id = $1
`

func (q *Queries) DeleteAddress(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAddress, id)
	return err
}

const getAddress = `-- name: GetAddress :one
SELECT id, client_id, title, city, street, phone, zip, lat, long, created_at, updated_at FROM addresses
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAddress(ctx context.Context, id int64) (Address, error) {
	row := q.db.QueryRow(ctx, getAddress, id)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Title,
		&i.City,
		&i.Street,
		&i.Phone,
		&i.Zip,
		&i.Lat,
		&i.Long,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAddresses = `-- name: ListAddresses :many
SELECT id, client_id, title, city, street, phone, zip, lat, long, created_at, updated_at FROM addresses
WHERE client_id = $1
`

func (q *Queries) ListAddresses(ctx context.Context, clientID int64) ([]Address, error) {
	rows, err := q.db.Query(ctx, listAddresses, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Address{}
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Title,
			&i.City,
			&i.Street,
			&i.Phone,
			&i.Zip,
			&i.Lat,
			&i.Long,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE addresses
SET
  title = $2,
  city = $3,
  street = $4,
  phone = $5,
  zip = $6,
  lat = $7,
  long = $8,
  updated_at = now()
WHERE
  id = $1
RETURNING id, client_id, title, city, street, phone, zip, lat, long, created_at, updated_at
`

type UpdateAddressParams struct {
	ID     int64         `json:"id"`
	Title  string        `json:"title"`
	City   string        `json:"city"`
	Street pgtype.Text   `json:"street"`
	Phone  pgtype.Text   `json:"phone"`
	Zip    pgtype.Text   `json:"zip"`
	Lat    pgtype.Float4 `json:"lat"`
	Long   pgtype.Float4 `json:"long"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.ID,
		arg.Title,
		arg.City,
		arg.Street,
		arg.Phone,
		arg.Zip,
		arg.Lat,
		arg.Long,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Title,
		&i.City,
		&i.Street,
		&i.Phone,
		&i.Zip,
		&i.Lat,
		&i.Long,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
